config/routes.rb
Rails.application.routes.draw do
  resources :songs
  root 'songs#index'
  get "/show_song" => 'songs#show_song', as: 'show_song'
  get "/mobile-index" => 'mobile#index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
end

app/models/song.rb
class Song < ActiveRecord::Base
  before_save :get_soundcloud_embed

  def slug
    title.gsub(/\s+/, "").gsub(/\W/,'').downcase
  end

  rails_admin do
    edit do
      field :title
      field :lyrics, :ck_editor
      field :soundcloud_url
      field :original_song
      field :original_song_url
      field :when_sung
      field :archived
    end
  end

  def as_json(options={})
    super(:only => [:title, :lyrics, :original_song, :soundcloud_url])
  end

  private

  def get_soundcloud_embed
    unless soundcloud_url.blank?
      client = SoundCloud.new(:client_id => ENV['SOUNDCLOUD_ID'])
      track_url = self.soundcloud_url
      embed_info = client.get('/oembed', :url => track_url)
      self.soundcloud_html = embed_info.html
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :detect_browser

  private

  def detect_browser
    case request.user_agent
      when /iPad/i
        request.variant = :tablet
      when /iPhone/i
        request.variant = :phone
      when /Android/i && /mobile/i
        request.variant = :phone
      when /Android/i
        request.variant = :tablet
      when /Windows Phone/i
        request.variant = :phone
      else
        request.variant = :desktop
    end
  end
end

app/controllers/mobile_controller.rb
class MobileController < ApplicationController
  layout 'mobile'
  def index
    @songs = Song.where(archived: [false,nil]).sort_by(&:title)
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def index
    @songs = Song.where(archived: [false,nil]).sort_by(&:title)

    respond_to do |format|
      format.json {render :json => @songs}
      format.html
      format.html.phone { redirect_to '/mobile-index' }
    end
  end

  def show_song
    @song = Song.find(params["song"])

    respond_to do |format|
      format.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_analytics.html.erb
<% if ENV["SEGMENT_IO_KEY"] %>
  <script type="text/javascript">
    window.analytics=window.analytics||[],window.analytics.methods=["identify","group","track","page","pageview","alias","ready","on","once","off","trackLink","trackForm","trackClick","trackSubmit"],window.analytics.factory=function(t){return function(){var a=Array.prototype.slice.call(arguments);return a.unshift(t),window.analytics.push(a),window.analytics}};for(var i=0;i<window.analytics.methods.length;i++){var key=window.analytics.methods[i];window.analytics[key]=window.analytics.factory(key)}window.analytics.load=function(t){if(!document.getElementById("analytics-js")){var a=document.createElement("script");a.type="text/javascript",a.id="analytics-js",a.async=!0,a.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.io/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n)}},window.analytics.SNIPPET_VERSION="2.0.9",
    window.analytics.load("<%= ENV["SEGMENT_IO_KEY"] %>");
    window.analytics.page();
  </script>
<% end %>

app/views/application/_flashes.html.erb
<% if flash.any? %>
  <div id="flash">
    <% flash.each do |key, value| -%>
      <div class="flash-<%= key %>"><%= value %></div>
    <% end -%>
  </div>
<% end %>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<%= render "analytics" %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="ROBOTS" content="NOODP" />
  <meta name="viewport" content="initial-scale=1" />
  <title>Unofficial Dark Clouds Songbook</title>
  <%= stylesheet_link_tag :application, media: "all" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= body_class %>">
  <%= render "flashes" -%>
  <%= yield %>
  <%= render "javascript" %>
</body>
</html>

app/views/layouts/mobile.html.haml
!!! 5
%html{:lang => 'en'}
  %head
    %meta{:charset => 'utf-8'}
    %meta{:name => 'viewport', :content => 'width=device-width, initial-scale=1'}
    %title= 'DC Songbook'
    %link{:rel => 'stylesheet', :href => '//fonts.googleapis.com/css?family=Roboto:400,300,300italic'}
    %link{:rel => 'stylesheet', :href => '//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.css'}
    %link{:rel => 'stylesheet', :href => '//code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.css'}
    %script{:src => '//code.jquery.com/jquery-2.1.3.min.js'}
    %script{:src => '//code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js'}
    = stylesheet_link_tag 'jquerymobile.nativedroid'
    = stylesheet_link_tag 'jquerymobile.blue'
    = stylesheet_link_tag 'jquerymobile.nativedroid.dark'
  %body
    = yield(:layout)

app/views/mobile/index.html.haml
#chants{data: {role: "page", theme: 'a'} }
  %div{data: {role: "header", position: "fixed", tap_toggle:"false", theme: 'b'}}
    %h1
      DARK CLOUDS SONGBOOK
  #scroll-area
    %div.ui-list-view{data: {role: 'content'}}
      %ul{data: {role:'listview', inset: 'false', icon: 'false', divider_theme: 'b'}}
        -@songs.each do |song|
          %li
            %a{href: "##{song.slug}"}
              =song.title

-@songs.each do |song|
  %div{id: "#{song.slug}", data: {role: 'page'}}
    %div{data: {role: 'header'}}
      %a{href: '#chants', data_ajax: 'false'}
        %i.fa.fa-chevron-left
      %h1=song.title
    .ui-content.song-box{data: {role: 'main'}}
      %h2 Lyrics
      .lyrics_box
        =raw(song.lyrics)
      %hr
      -unless song.original_song.blank?
        -if song.original_song_url.blank?
          %h3 Sung to the tune of:
          #{song.original_song}
        -else
          %h3 Sung to the tune of:
          #{link_to song.original_song, song.original_song_url}
      -unless song.soundcloud_url.blank?
        %h4 Soundcloud:
        #{link_to song.soundcloud_url, song.soundcloud_url}
:css
  .song-box{
    padding-left: 25px;
    line-height: 1.2em;
    font-size: 1.2em;
  }

app/views/songs/_song.html.haml
%div{class: "card", id: song.slug}
  .card-image
  .card-header
    =song.title
    -unless song.original_song.blank?
      %br
      .original_song
        sung to the tune of #{song.original_song}
  .card-copy
    =raw(song.lyrics)
  -unless song.soundcloud_html.blank?
    .soundcloud_iframe
      =raw(song.soundcloud_html.gsub('="400"', '=100'))

app/views/songs/index.html.haml
%header
  %h1#header-text
    Unofficial Dark Clouds Songbook
    =image_tag("cloud.jpeg", height: '50')
.container
  %ul#menu
    -@songs.each do |song|
      %li
        .lyric_link
          =link_to song.title, show_song_path(song: song), remote:true
  #songs
    #card-holder
%footer
  %p
    Code lives on
    %i.fa.fa-github
    =link_to "(Pull requests welcome!)", "https://github.com/estiens/dark-clouds-lyrics"
  %p.tiny
    Original mobile code by
    =link_to "Drew Jensen", "https://github.com/DrewOJensen"
    |
    Rails code and desktop code by
    =link_to "Eric Stiens", "https://github.com/estiens"
    |
    Dark Clouds live
    =link_to "here", "http://www.dark-clouds.com/"

app/views/songs/mobile-index.html.haml
#chants{data: {role: "page", theme: 'a'} }
  %div{data: {role: "header", position: "fixed", tap_toggle:"false", theme: 'b'}}
    %h1
      DC SONGBOOK
  #scroll-area
    %div.ui-list-view{data: {role: 'content'}}
      %ul{data: {role:'listview', inset: 'false', icon: 'false', divider_theme: 'b'}}
        -@songs.each do |song|
          %li
            %a{href: "##{song.slug}"}
              =song.title

-@songs.each do |song|
  %div{id: "#{song.slug}", data: {role: 'page'}}
    %div{data: {role: 'header'}}
      %a{href: '#chants', data_ajax: 'false'}
        %i.fa.fa-chevron-left
      %h1=song.title
    .ui-content{data: {role: 'main'}}
      %h2 Lyrics
      .lyrics_box
        =raw(song.lyrics)
      -unless song.original_song.blank?
        -if song.original_song_url.blank?
          %h5 Sung to the tune of:
          #{song.original_song}
        -else
          %h4 Sung To The Tune Of:
          #{link_to song.original_song, song.original_song_url}
      -unless song.soundcloud_url.blank?
        %h4 Soundcloud:
        #{link_to song.soundcloud_url, song.soundcloud_url}

app/views/songs/show_song.js.erb
$('#card-holder').html("<%= j render(:partial => 'songs/song', :locals => {:song => @song}) %>")
$('#card-holder').sticky({topSpacing:125});